apiVersion: v1
kind: Pod
metadata:
  name: dns-test
spec:
  # BUG: DNS was "hard-coded" to 10.96.0.99, which is NOT the cluster DNS (kube-dns = 10.96.0.10)
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 10.96.0.99
    searches:
      - default.svc.cluster.local
      - svc.cluster.local
      - cluster.local
  containers:
    - name: dns-test
      image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.7
      command:
        - sleep
        - "3600"
