apiVersion: v1
kind: Pod
metadata:
  name: errpull-demo
spec:
  containers:
    - name: app
      # This repository does not exist on Docker Hub
      image: docker.io/ajijuttam/notes-api-does-not-exist:v1
