#!/bin/bash
# System Information Script
# Author: Ajij Uttam (24bcs10103)

# ---- variables ----
CURRENT_DATE=$(date)
HOST_NAME=$(hostname)
USER_NAME=$(whoami)

echo "========== System Information =========="
echo "Date      : $CURRENT_DATE"
echo "Hostname  : $HOST_NAME"
echo "Username  : $USER_NAME"
echo

echo "---------- Disk Usage ----------"
df -h /
echo

echo "---------- Running Processes (first 10) ----------"
ps -eo pid,user,pcpu,pmem,comm | head -11 | cut -c1-90
echo

# ---- user input ----
read -p "Enter a name for the report directory: " DIR_NAME
DIR_NAME=${DIR_NAME:-sysinfo_report}

# ---- create directory and file ----
mkdir -p "$DIR_NAME"
REPORT_FILE="$DIR_NAME/processes.txt"
touch "$REPORT_FILE"

# ---- store running processes using > redirection ----
echo "Process report generated by $USER_NAME on $HOST_NAME at $CURRENT_DATE" > "$REPORT_FILE"
ps aux >> "$REPORT_FILE"

echo "Directory created : $DIR_NAME"
echo "Report file       : $REPORT_FILE"
echo "Lines written     : $(wc -l < "$REPORT_FILE")"
echo "========== Done =========="
